# datasource
spring:
  application:
    name: trace2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  kafka:
    bootstrap-servers: 192.168.1.200:9092,192.168.1.201:9092,192.168.1.202:9092
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: kafka



server:
  port: 8084
